sudo: false
language: node_js
node_js:
- 'node'
env:
  global:
  - secure: K/sjN0FPNLX2QMIyVJoZ5tk7mU/D0yd0XLEm8M3VEviDq3vWIOKWS8nz63n9kD+ADpn5WBc3HOh1kPzj39oPT8O21gg5P6l08rPLjQEclMdvrNsXfkSobJVQI8rt2vqWyQt4Z7olt+89qExf9XcOG0fvj7UfJvM+CZ0rXxMKjCo=
  - secure: C5o/6f/98meI5zI7gayvsev0MhMxZ0H/wvOJv960bAOqfjotIRoeBtTEREAPcB8fCTMXLnds5nGgLANxKC3gXdGirKUxX/YJMRPwr0s5skGFLyGR7c0BY3VXRvSBI4UaxSxQGDm+lzUbhDqzyMFpAzTI3/F/DLSWoQgshGzIr3s=
